config/routes.rb
Rails.application.routes.draw do


  get 'teams/index'

  get 'teams/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :managements, only: [:index]
  devise_for :managements
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

   namespace :managements do
      resources :projects  do
        resources :tasks
      end
        resources :teams
        resources :tasks
        resources :products
        resources :contacts do
          resources :comments
        end
    end

      resources :projects, only: [:index, :show]
        resources :products, only: [:index, :show]
        resources :contacts, only:[:new, :create]
        resources :teams , only: [:index, :show]

  ActiveAdmin.routes(self)
    root 'home#index'

    authenticated :user do
       root 'users#index', as: "authenticated_root"
     end
     authenticated :managment do
       root "management#index"
     end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :contact
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/management.rb
class Management < ApplicationRecord
  mount_uploader :managementimage, ManagementimageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable, :lockable

 has_many :projects
 has_many :contacts
 has_many :teams

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :management
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :projectimage, ProjectimageUploader
  belongs_to :management
  belongs_to :team
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :management
  has_many :projects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        contact = @contact
        ContactmailerMailer.contact_email(contact).deliver
        format.html { redirect_to root_path, notice: 'Hi, Will get in touch soon.' }
        format.json { redirect_to root_path, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end

    end
  end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_contact
        @contact = contact.find(params[:id])
      end


      # Never trust parameters from the scary internet, only allow the white list through.
      def contact_params
        params.require(:contact).permit(:name, :email, :ideaname, :country, :phone, :message, :lead, :management_id )
      end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @projects = Project.all.order('created_at DESC')
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :set_project, only: [:show]

    # GET /projects
    # GET /projects.json
    def index
      @projects = Project.all.order('created_at DESC')
    end
  def show
    @projects = Project.all.order('created_at DESC')
  end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find(params[:id])
      end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all.order('created_at DESC')
  end
def show
  @projects = Project.all.order('created_at DESC')

end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zonia:Admin</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="" />

  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  <script type="applijewelleryion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

</head>
<body>
  <div class="wrapper">
		<div class="sidebar" data-color="purple" data-image="img/sidebar-5.jpg">
        <%= render "adminusers/sidebar" %>
        <%= render "adminusers/header" %>
    <%= yield %>

  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zonia Solutions|| Software development & Cloud Services</title>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  

 <!--/Preloader -->

<!-- Header -->
<%= render "shared/header" %>
    <%= yield %>
<%= render "shared/footer" %>
<!-- Modal: Get In Touch -->
<div class="modal fade" id="get-in-touch" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title">Get In Touch</h4>
            </div>

            <div class="modal-body">
                <div class="row">

                    <!-- Contact Form -->
                    <div class="col-md-12 contact-form">
                        <form class="form-ajax" method="post">
                            <input type="hidden" name="form" value="Get In Touch Modal">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <input type="text" name="name" class="form-control" placeholder="Your Name... *" required>
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="email" name="email" class="form-control" placeholder="E-mail address... *" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <textarea name="message" class="form-control" placeholder="Message... "></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12 text-center">
                                    <button type="submit" class="btn btn-theme"><i class="icon fa fa-fw fa-paper-plane-o"></i> <span class="text">Send Message</span></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /Contact Form -->


                </div>
            </div>

        </div>
    </div>
</div>
<!-- Modal: /Get In Touch -->

<!-- Modal: Result Message -->
<div class="modal fade" id="result" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title">Sending message</h4>
            </div>

            <div class="modal-body">

                <div class="result-icon">
                    <div class="icon-border">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" preserveAspectRatio="none">
                            <circle cx="8" cy="8" r="6.215" transform="rotate(90 8 8)"></circle>
                        </svg>
                        <i class="icon fa fa-check"></i>
                    </div>
                </div>

                <p class="modal-result h4 text-center"></p>
            </div>

        </div>
    </div>
</div>
<!-- /Modal: Result Message -->
<script text="text/javascript">
$(function(){ // this replaces document.ready
  setTimeout(function(){
    $('#preloader').fadeOut('slow', function() {
      $(this).remove();
    });
  }, 1500);
});
</script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zonia:Admin</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="" />

  <%= stylesheet_link_tag    'management', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'management', 'data-turbolinks-track': 'reload' %>
  <script type="applijewelleryion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

</head>

<body style="width:100%;   background-color: #FAFAFA">



    <div class="bg">

    </div>



    <section>

      <div class="container">
        <div class="col-md-6 col-md-offset-3 p "  >

          <div class="card" style="padding:20px;">



            <div class="card-block">
              <%= yield %>
            </div>

        </div>
          </div>
  </div>
  </section>




</body>
</html>

app/views/layouts/management.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zonia:Management</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="" />

  <%= stylesheet_link_tag    'management', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'management', 'data-turbolinks-track': 'reload' %>
  <script type="applijewelleryion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

</head>
<body>
  <div class="wrapper">
		<div class="sidebar" data-color="purple" >
        <%= render "managements/sidebar" %>
        <%= render "managements/header" %>
    <%= yield %>

  </div>
</div>
</body>
</html>

app/views/shared/_banner.html.erb
    <!-- Slider -->
    <div id="owl-carousel" class="slider owl-carousel owl-theme">

        <!-- Slide -->
        <div class=" i item mask mask-black" style="background-image: url(<%= asset_path 'bgg1.jpg' %>); " data-stellar-background-ratio="0.4">
            <div class="full-wh relative" data-stellar-ratio="0.5">
                <div class="container" >
                    <div class="col-md-6 col-md-offset-2 relative">
                        <h1 class="animated fadeInDown wow" data-wow-delay="0.2s">LOOKING TO CREATING A SUCCESSFUL ONLINE PRESENCE?</h1>
                        <div class="subtitle animated fadeInUp wow" data-wow-duration="0.9s" data-wow-delay="0.5s">
                        <p style="font-size:18px;">  we work with game-changing brands, inspired companies, and global influencers.
                            Whether you’re just starting out or evolving your brand.The first step to growing a brand online is to drive qualified leads to your website or mobile app. Having a user-friendly experience is an important part of any successful business strategy, but generating relevant traffic is essential to having a strong conversion rate.
                            We are here to offer you that</p>
                        </div>
                        <div class="animated fadeInUp wow" data-wow-delay="1.0s">
                            <a href="#" class="btn btn-rounded btn-white-o" data-toggle="modal" data-target="#get-in-touch">Get In Touch</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Slide -->

        <!-- Slide -->
        <div class=" i item mask mask-black" style="background-image: url(<%= asset_path 'bgg2.jpg' %>);" data-stellar-background-ratio="0.4">
            <div class="full-wh relative" data-stellar-ratio="0.5">
                <div class="container" >
                    <div class="col-md-6 col-md-offset-2 relative">
                        <h1 class="animated fadeInDown wow" data-wow-delay="0.2s">WELCOME TO ZONIA</h1>
                        <div class="subtitle animated fadeInUp wow" data-wow-duration="0.9s" data-wow-delay="0.5s">
                            <p style="font-size:18px;">
                              We are a group of professional,  web design and development agency devoted to  crafting custom websites for forward thinking brands and businesses. In Africa, America and the eastern world. we know what it takes to create an effective digital strategy, user friendly web design and online marketing to help you stand out from the crowd.
                             </p>
                        </div>
                        <div class="animated fadeInUp wow" data-wow-delay="1.0s">
                            <a href="#" class="btn btn-rounded btn-white-o" data-toggle="modal" data-target="#get-in-touch">Get In Touch</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Slide -->

        <!-- Slide
        <div class=" i item mask mask-black" style="background-image: url(<%= asset_path 'bbg3.jpg' %>) ;" data-stellar-background-ratio="0.4">
            <div class="full-wh relative" data-stellar-ratio="0.5">
                <div class="container" >
                    <div class="col-md-6 col-md-offset-2 relative">
                        <h1 class="animated fadeInDown wow" data-wow-delay="0.2s">INNOVATIVE & CUSTOMER-FOCUSED</h1>
                        <div class="subtitle animated fadeInUp wow" data-wow-duration="0.9s" data-wow-delay="0.5s">
                          <p>
                            Let us maximize your business potential
                               with the latest and innovative technologies
                               We deliver visually appealing, innovative and feature-rich web solutions centered towards your business.
Our digital marketing programs are implemented to drive real growth to your business.

                        </div>
                        <div class="animated fadeInUp wow" data-wow-delay="1.0s">
                            <a href="#" class="btn btn-rounded btn-white-o" data-toggle="modal" data-target="#get-in-touch">Get In Touch</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>-->
        <!-- /Slide -->


    </div>
    <!-- /Slider -->

</header>
<script type="text/javascript">
$(document).ready(function() {
$("#owl-carousel").owlCarousel({

slideSpeed: 500,
paginationSpeed: 500,
singleItem: true,
    autoPlay:true,
    autoPlayTimeout:5000,
    autoPlayHoverPause:false,
    loop:true,
    items:2,
    pagination:true,
    responsive:true,
    transitionStyle:'fadeUp'
// "singleItem:true" is a shortcut for:
// items : 1,
// itemsDesktop : false,
// itemsDesktopSmall : false,
// itemsTablet: false,
// itemsMobile : false
});
});
</script>
<!-- /Header -->

app/views/shared/_bottom.html.erb
<section id="start" class="section">
    <div class="container">

        <!-- Section Header -->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <header class="text-center">
                    <h2 class="section-title underline">Easy To Start With Zonia Solutions</h2>
                    <p class="section-subtitle">
                        Here are why customers choose us and how easy it is to work with us
                    </p>
                </header>
            </div>
        </div>
        <!-- /Section Header -->

        <!-- Section Content -->
        <div class="row section-content">

            <!-- Step Block -->
            <div class="col-sm-4 animated fadeIn wow" data-wow-duration="0.9s">
                <div class="media step">
                    <div class="media-left media-middle h4">
                        <div class="number">1</div>
                    </div>
                    <div class="media-body">
                        <div class="h4 title">Talk To Us</div>
                        <p class="description">
                            It is a long established fact that  communication is a key factor to achieveing yoor goals, talk to us with our 24/7 customer support and  consultation
                        </p>
                    </div>
                </div>
            </div>
            <!-- /Step Block -->

            <!-- Step Block -->
            <div class="col-sm-4 animated fadeIn wow" data-wow-duration="0.9s" data-wow-delay="0.4s">
                <div class="media step">
                    <div class="media-left media-middle h4">
                        <div class="number">2</div>
                    </div>
                    <div class="media-body">
                        <div class="h4 title">Send Query</div>
                        <p class="description">
                            We will send you a simple and user friendly anwers and technical costs and solution to achieve your aim
                        </p>
                    </div>
                </div>
            </div>
            <!-- /Step Block -->

            <!-- Step Block -->
            <div class="col-sm-4 animated fadeIn wow" data-wow-duration="0.9s" data-wow-delay="0.8s">
                <div class="media step">
                    <div class="media-left media-middle h4">
                        <div class="number">3</div>
                    </div>
                    <div class="media-body">
                        <div class="h4 title">Get Service</div>
                        <p class="description">
                            No need to look far to get the services you need to build your goals. We provide them for you
                        </p>
                    </div>
                </div>
            </div>
            <!-- /Step Block -->

        </div>
        <!-- /Section Content -->

    </div>
</section>
<!-- /Section: How To Start -->

]
<!-- Section: Contact Information -->
<section id="contact-information" class="section section-small no-pb bg-dark">
    <div class="container">



        <!-- Section Content -->
        <div class="row animated fadeIn wow" data-wow-duration="0.9s">
            <div class="col-md-8 col-md-offset-2 col-sm-12">
                <div class="row">

                    <div class="col-sm-4 col-xs-12">
                        <div class="media contact">
                            <div class="media-left">
                                <span class="icon icon_map_alt"></span>
                            </div>
                            <div class="media-body info h5">
                                <span>Our Address</span>
                              10 Adelabun Ahalaji Animashaun, Surulere, Lagos
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-xs-12">
                        <div class="media contact">
                            <div class="media-left">
                                <span class="icon icon_mail_alt"></span>
                            </div>
                            <div class="media-body info h5">
                                <span>E-mail</span>
                                support@zonia.co
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-xs-12">
                        <div class="media contact">
                            <div class="media-left">
                                <i class="icon icon_mobile"></i>
                            </div>
                            <div class="media-body info h5">
                                <span>Phone Number</span>
                                +234 (816) 186-9777
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- /Section Content -->

    </div>
</section>
<!-- /Section: Contact Information -->

<!-- Section: Contact -->
<section id="contact" class="section">
    <div class="container">

        <!-- Section Header -->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <header class="text-center">
                    <h2 class="section-title underline">Contact Us</h2>
                    <p class="section-subtitle">
                        There are many variations nd possibilties of what may or may not be needed to get your ideas online
                        . <strong>You are free to consult us anytime </strong>
                      </p>
                </header>
            </div>
        </div>
        <!-- /Section Header -->

        <!-- Section Content -->
        <div class="row section-content">

            <!-- Contact Form -->
          <div class="text-center">
            <%=link_to "Consult Us", "", class: "btn btn-theme" %>
          </div>

        </div>
        <!-- /Section Content -->

    </div>
</section>
<!-- /Section: Contact -->

</main>
<!-- /Main -->

app/views/shared/_header.html.erb
<header id="home" class="header">

    <!-- Navigation -->
    <nav id="navigation" class="navbar affix">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <!-- Navigation Header -->
                    <div class="navbar-header">

                        <!-- Toggle Button -->
                        <button type="button"
                                class="navbar-toggle collapsed"
                                data-toggle="collapse"
                                data-target="#main-menu"
                                aria-expanded="false"
                                aria-controls="main-menu">

                            <span class="sr-only">Toggle Navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>

                        </button>
                        <!-- /Toggle Button -->

                        <!-- Brand -->
                        <a href="#" class="brand">

                            <!-- Logo Big -->
                            <div class="big">
                                <span class="navbar-brand"><%=image_tag 'logo.png', :class => "lo" %></span> Zonia Hi-Tech Solutions
                            </div>
                            <!-- /Logo Big -->

                            <!-- Logo Small -->
                            <div class="small">
                                <span class="navbar-brand" ><%=image_tag 'logo.png', :class => "lo"  %></span>
                            </div>
                            <!-- /Logo Small -->

                        </a>
                        <!-- /Brand -->

                    </div>
                    <!-- /Navigation Header -->

                    <!-- Navigation -->
                    <div id="main-menu" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">

                          <%if management_signed_in? %>
                              <li><a href="#"> Welcome <%= current_management.name %></a></li>
                          <li><%= link_to "Dashboard", managements_path, class: "smooth-scroll" %></li>
                            <li><%= link_to "Log Out!!", destroy_management_session_path, :method => :delete, :class =>"smooth-scroll"  %>

                          <%else %>
                            <li class="Smooth-scroll">
                                <%= link_to "Home", root_path %>
                            </li>
                            <li> <%= link_to "Projects", projects_path, class: "smooth-scroll" %></li>

                            <li><a class="smooth-scroll" href="#services">Services</a></li>
                          
                                    <li><%= link_to "Team", teams_path %></li>


                            <li><a class="smooth-scroll" href="#testimonials">Testimonials</a></li>

                            <li><%= link_to "Contact", new_contact_path %></li>
                          <% end %>
                        </ul>
                    </div>
                    <!-- /Navigation -->

                </div>
            </div>
        </div>
    </nav>
    <!-- /Navigation -->
    <% if notice %>
    <div class="container" style="position:absolute; top:100px; left:210px; z-index:10;">
      <div class="col-md-8 col-md-offset-2">
    <div class="alert alert-success fade in">
       <a href="#" class="close" data-dismiss="alert">&times;</a>
      <p><%= notice %> </p>
    </div>
    </div>
      </div>
      <% elsif alert %>
      <div class="container">
        <div class="col-md-12">
          <div class="alert alert-danger fade in">
             <a href="#" class="close" data-dismiss="alert">&times;</a>
            <p><%= alert %></p>
          </div>
        </div>
      </div>
          <% end %>

app/views/shared/_projects.html.erb
<section id="projects" class="section section-small no-pb bg-light-gray">
    <div class="container-fluid">

        <!-- Section Header -->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <header class="text-center">
                    <h2 class="section-title underline"> Some Of Our Latest Projects</h2>
                    <p class="section-subtitle">
                      We are proud to have a number of satisfied clients whom we have helped beat the competition.
  The varied range of design and development projects are enough to reflect the professionalism and experience that we have.
                    </p>
                </header>
            </div>
        </div>
        <!-- /Section Header -->

        <div class="row section-content animated fadeIn wow" data-wow-duration="0.9s">
                    <% @projects.each do |project| %>
            <!-- Project Image -->
            <div class="col-md-3 col-sm-6 col-xs-12 project-col">
                  <%= link_to image_path((project.projectimage_url)), class: "project-item image-popup" do %>

                    <div class="gallery-image">
                          <%= image_tag (project.projectimage_url.to_s) %>
                    </div>

                <% end %>
            </div>
            <!-- /Project Image -->
<% end %>


        </div>

    </div>
</section>