config/routes.rb
Rails.application.routes.draw do


  get 'teams/index'

  get 'teams/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :managements, only: [:index]
  devise_for :managements
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

   namespace :managements do
      resources :projects  do
        resources :tasks
      end
        resources :teams
        resources :tasks
        resources :products
        resources :contacts do
          resources :comments
        end
    end

      resources :projects, only: [:index, :show]
        resources :products, only: [:index, :show]
        resources :contacts, only:[:new, :create]
        resources :teams , only: [:index, :show]

  ActiveAdmin.routes(self)
    root 'home#index'

    authenticated :user do
       root 'users#index', as: "authenticated_root"
     end
     authenticated :managment do
       root "management#index"
     end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/management.rb
class Management < ApplicationRecord
  mount_uploader :managementimage, ManagementimageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable, :lockable

 has_many :projects
 has_many :contacts
 has_many :teams

end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :projectimage, ProjectimageUploader
  belongs_to :management
  belongs_to :team
end

app/controllers/management/projects_controller.rb
class Management::ProjectsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects/new
  def index
    @projects = Project.where(management_id: current_management)
  end
  def new
    @project = current_management.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_management.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to management_projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:details, :title, :client, :projectimage, :management_id, :links )
    end
  end

end

app/controllers/managements/comments_controller.rb
class Managements::CommentsController < ApplicationController
  layout 'management'
  before_action :find_comments, except: [:create, :new, :index]



  def create
    @contact = Contact.find(params[:contact_id])
    @comment = @contact.comments.create(params[:comment].permit(:body, :management_id, :contact_id, :email))
    @comment.management_id = current_management.id
    if @comment.save
      management = Management.find_by_id(@contact.management_id)
      comment = @comment
      contact = @contact
      CommentMailer.comment_email(management, contact, comment).deliver
      redirect_to managements_contact_path(@contact), notice: "comment Sent successffully"
    else
      redirect_to managements_contact_path(@contact), notice: "Please Try again Your coustomer is waiting"
    end
  end

  private
  def find_comments
    @comment = Comment.find(params[:id])
  end

  def comments_params
    params.require(:comment).permit(:body, :management_id, :contact_id)
  end
end

app/controllers/managements/contacts_controller.rb
class Managements::ContactsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # GET /contacts/new
  def index
  @contacts = Contact.all.order('created_at DESC')

 end

  def show
  end
  def new
    @contact = current_management.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_management.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to managements_contacts_path, notice: 'Hi, Will get in touch soon.' }
        format.json { redirect_to root_path, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end

    end
  end


  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to managements_contacts_path, notice: 'contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to managements_contacts_path, notice: 'contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :ideaname, :country, :phone, :message, :management_id )
    end
end

app/controllers/managements/products_controller.rb
class Managements::ProductsController < ApplicationController
end

app/controllers/managements/projects_controller.rb
class Managements::ProjectsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects/new
  def index
  @projects = Project.all.order('created_at DESC')

 end
  def new
    @project = current_management.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_management.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to management_projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:details, :title, :client, :projectimage, :management_id, :links, :team_id )
    end


end

app/controllers/managements/teams_controller.rb
class Managements::TeamsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_team, only: [:show, :edit, :update]
  # GET /teams/new
  def index
  @teams = Team.all.order('created_at DESC')

 end
  def new
    @team = current_management.teams.build
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = current_management.teams.build(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_url, notice: 'team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to management_teams_path, notice: 'team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :github, :medium, :skill_1, :skill_2, :skill_others, :avatar, :twitter, :cv, :management_id, :bio, :position, :steamit )
    end

end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  layout "management"
  before_action :authenticate_management!
  before_action :find_managements, only: [:index]
  before_action :find_projects, only: [:index]

  def index
  @managements = Management.where(management_id: current_management).order('created_at DESC')
  @projects = Project.where(management_id: current_management).order('created_at DESC')
  @contacts = Contact.all.order('created_at DESC')
  @teams = Team.all

  end


private
def find_managements
  if params[:id].nil?
    @management = current_management
  else
  @management = current_management
end
end
def find_projects
  @projects = Project.where(management_id: @management).order('created_at DESC')
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :set_project, only: [:show]

    # GET /projects
    # GET /projects.json
    def index
      @projects = Project.all.order('created_at DESC')
    end
  def show
    @projects = Project.all.order('created_at DESC')
  end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find(params[:id])
      end


end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/managements/comments_helper.rb
module Managements::CommentsHelper
end

app/helpers/managements/contacts_helper.rb
module Managements::ContactsHelper
end

app/helpers/managements/mails_helper.rb
module Managements::MailsHelper
end

app/helpers/managements/teams_helper.rb
module Managements::TeamsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/staff/projects_helper.rb
module Staff::ProjectsHelper
end

app/views/managements/projects/_edit_form.html.erb
<%= simple_form_for([@managementmanagement, :managements, @project], :url => managements_project_path(@project)) do |f| %>
<%= f.error_notification %>


  <div class="form-group">
    <div class="col-md-12">

    <%= f.input :title, class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
    <div class="col-md-12">
    <%= f.input :details, class: "form-control", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= f.input :client, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= f.input :projectimage, as: :file,  class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <%= f.input :links,  class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <%= f.submit :submit, class: "btn  btn-picasso" %>
  </div>
</div>
<% end %>

app/views/managements/projects/_form.html.erb
<%= simple_form_for([@management, :managements, @project], :url => managements_projects_path) do |f| %>
<%= f.error_notification %>


  <div class="form-group">
    <div class="col-md-12">

    <%= f.input :title, class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
    <div class="col-md-12">
    <%= f.input :details, class: "form-control", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= f.input :client, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= f.input :projectimage, as: :file,  class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <%= f.input :links,  class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <%= f.input :developer, :as => :select, :collection => Team.all.map{|c| ["#{c.github}, #{c.name}", c.id]} %>

  </div>
</div>
<div class="form-group">
  <div class="col-md-12">
    <%= f.submit :submit, class: "btn  btn-picasso" %>
  </div>
</div>
<% end %>

app/views/managements/projects/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 card">

          <div class="header">
            <h4 class="title">Edit Project</h4>
          </div>
          <div class="content">
            <%= render 'edit_form' %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>

app/views/managements/projects/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 card">
        <div class="header">
          <h4 class="title">All Projects </h4>
        </div>
        <div class="content">
          <div class="projects-list">
            <% @projects.each do |project| %>
              <div class="col-sm-4 col-xs-12 project">
                  <%= link_to project do %>
                      <div class="project-image-wrapper">
                          <div class="project-image" style="height:200px;">
                              <%= image_tag (project.projectimage_url.to_s) %>

                              <div class="information">
                                  <h3 class="title"><%= project.title %></h3>
                                  <h5 class="title"><%= link_to 'Edit', edit_managements_project_path(project) %></span>
                                  <h5 class="title"><%= link_to 'Destroy', managements_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></span>
                              </div>
                          </div>
                      </div>
                  <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-2">

                          <div class="image">
                              <%= link_to new_managements_project_path, class: "btn btn-info btn-fill pull-right" do %>
                                  Add Project
                                 <% end %>
                      </div>
        </div>
          </div>
        </div>
      </div>

app/views/managements/projects/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 card">

          <div class="header">
            <h4 class="title">New Projects</h4>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>