config/routes.rb
Rails.application.routes.draw do


  get 'teams/index'

  get 'teams/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :managements, only: [:index]
  devise_for :managements
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

   namespace :managements do
      resources :projects  do
        resources :tasks
      end
        resources :teams
        resources :tasks
        resources :products
        resources :contacts do
          resources :comments
        end
    end

      resources :projects, only: [:index, :show]
        resources :products, only: [:index, :show]
        resources :contacts, only:[:new, :create]
        resources :teams , only: [:index, :show]

  ActiveAdmin.routes(self)
    root 'home#index'

    authenticated :user do
       root 'users#index', as: "authenticated_root"
     end
     authenticated :managment do
       root "management#index"
     end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/management.rb
class Management < ApplicationRecord
  mount_uploader :managementimage, ManagementimageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable, :lockable

 has_many :projects
 has_many :contacts
 has_many :teams

end

app/controllers/management/projects_controller.rb
class Management::ProjectsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects/new
  def index
    @projects = Project.where(management_id: current_management)
  end
  def new
    @project = current_management.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_management.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to management_projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:details, :title, :client, :projectimage, :management_id, :links )
    end
  end

end

app/controllers/managements/comments_controller.rb
class Managements::CommentsController < ApplicationController
  layout 'management'
  before_action :find_comments, except: [:create, :new, :index]



  def create
    @contact = Contact.find(params[:contact_id])
    @comment = @contact.comments.create(params[:comment].permit(:body, :management_id, :contact_id, :email))
    @comment.management_id = current_management.id
    if @comment.save
      management = Management.find_by_id(@contact.management_id)
      comment = @comment
      contact = @contact
      CommentMailer.comment_email(management, contact, comment).deliver
      redirect_to managements_contact_path(@contact), notice: "comment Sent successffully"
    else
      redirect_to managements_contact_path(@contact), notice: "Please Try again Your coustomer is waiting"
    end
  end

  private
  def find_comments
    @comment = Comment.find(params[:id])
  end

  def comments_params
    params.require(:comment).permit(:body, :management_id, :contact_id)
  end
end

app/controllers/managements/contacts_controller.rb
class Managements::ContactsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # GET /contacts/new
  def index
  @contacts = Contact.all.order('created_at DESC')

 end

  def show
  end
  def new
    @contact = current_management.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_management.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to managements_contacts_path, notice: 'Hi, Will get in touch soon.' }
        format.json { redirect_to root_path, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end

    end
  end


  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to managements_contacts_path, notice: 'contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to managements_contacts_path, notice: 'contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :ideaname, :country, :phone, :message, :management_id )
    end
end

app/controllers/managements/products_controller.rb
class Managements::ProductsController < ApplicationController
end

app/controllers/managements/projects_controller.rb
class Managements::ProjectsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects/new
  def index
  @projects = Project.all.order('created_at DESC')

 end
  def new
    @project = current_management.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_management.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to management_projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:details, :title, :client, :projectimage, :management_id, :links, :team_id )
    end


end

app/controllers/managements/teams_controller.rb
class Managements::TeamsController < ApplicationController
  layout 'management'
    before_action :authenticate_management!
  before_action :set_team, only: [:show, :edit, :update]
  # GET /teams/new
  def index
  @teams = Team.all.order('created_at DESC')

 end
  def new
    @team = current_management.teams.build
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = current_management.teams.build(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_url, notice: 'team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to management_teams_path, notice: 'team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :github, :medium, :skill_1, :skill_2, :skill_others, :avatar, :twitter, :cv, :management_id, :bio, :position, :steamit )
    end

end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  layout "management"
  before_action :authenticate_management!
  before_action :find_managements, only: [:index]
  before_action :find_projects, only: [:index]

  def index
  @managements = Management.where(management_id: current_management).order('created_at DESC')
  @projects = Project.where(management_id: current_management).order('created_at DESC')
  @contacts = Contact.all.order('created_at DESC')
  @teams = Team.all

  end


private
def find_managements
  if params[:id].nil?
    @management = current_management
  else
  @management = current_management
end
end
def find_projects
  @projects = Project.where(management_id: @management).order('created_at DESC')
end
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/managements/comments_helper.rb
module Managements::CommentsHelper
end

app/helpers/managements/contacts_helper.rb
module Managements::ContactsHelper
end

app/helpers/managements/mails_helper.rb
module Managements::MailsHelper
end

app/helpers/managements/teams_helper.rb
module Managements::TeamsHelper
end

app/views/managements/_header.html.erb
<div class="main-panel">
		<nav class="navbar navbar-default navbar-fixed">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Dashboard</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-left">
						<li>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-dashboard"></i>
								<p class="hidden-lg hidden-md">Dashboard</p>
							</a>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-globe"></i>
								<b class="caret hidden-sm hidden-xs"></b>
								<span class="notification hidden-sm hidden-xs">5</span>
								<p class="hidden-lg hidden-md">
									5 Notifications
									<b class="caret"></b>
								</p>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">Notification 1</a></li>
								<li><a href="#">Notification 2</a></li>
								<li><a href="#">Notification 3</a></li>
								<li><a href="#">Notification 4</a></li>
								<li><a href="#">Another notification</a></li>
							</ul>
						</li>
						<li>
							<a href="">
								<i class="fa fa-search"></i>
								<p class="hidden-lg hidden-md">Search</p>
							</a>
						</li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<% if management_signed_in? %>
              <a>
								<p><%= current_management.email %></p>
              </a>
							<%end %>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<p>
									Dropdown
									<b class="caret"></b>
								</p>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</li>
						<li>
							<%= link_to destroy_management_session_path, :method => :delete do %>
								<p>Log out</p>
							<% end %>
						</li>
						<li class="separator hidden-lg hidden-md"></li>
					</ul>
				</div>
			</div>
		</nav>

app/views/managements/_sidebar.html.erb
<div class="sidebar-wrapper ">
			<div class="logo">
				<a class="simple-text">
          <% if management_signed_in? %>
					<%= current_management.name %>
          <% end%>
				</a>
			</div>

			<ul class="nav">
				<li class="active">
					<%= link_to managements_path do%>
						<i class="pe-7s-dashboard"></i>
						<p>Dashboard</p>
					<% end %>
				</li>
				<li>
					<%= link_to edit_management_registration_path do%>
						<i class="pe-7s-user"></i>
						<p>User Profile</p>
					<% end %>
				</li>
				<li>
					<%= link_to managements_projects_path  do %>
						<i class="pe-7s-note2"></i>
						<p>Projects</p>
					<% end %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="pe-7s-users"></i>
						<p class="">
							Contact & Leads
							<b class="caret"></b>
						</p>
					</a>
					<ul class="dropdown-menu" >
						<li >
					<%= link_to managements_contacts_path  do %>
						<i class="pe-7s-users"></i>
						<p>Contact Book</p>
					<% end %>
				</li>
				<li >
			<%= link_to new_managements_contact_path  do %>
				<i class="pe-7s-users"></i>
				<p>  Add New Contact </p>
			<% end %>
		</li>
			</ul>
		</li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<i class="pe-7s-users"></i>
				<p class="">
					Teams
					<b class="caret"></b>
				</p>
			</a>
			<ul class="dropdown-menu" >
				<li>
					<%= link_to managements_teams_path do %>
						<i class="pe-7s-users"></i>
						<p>Team Memebers</p>
					<% end %>
				</li>
				<li>
					<%= link_to new_managements_team_path do %>
						<i class="pe-7s-users"></i>
						<p>New Team Memebers</p>
					<% end %>
				</li>
			</ul>
		</li>
				<li class="active-pro">
					<%=link_to root_path do %>
						<i class="pe-7s-rocket"></i>
						<p>Back To Zonia</p>
					<% end %>
				</li>
			</ul>
		</div>
	</div>

app/views/managements/index.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">

          <%= link_to managements_projects_path do %>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-warning text-center">
                                  <i class="pe-7s-note2"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Projects</p>
                                  <%= Project.where(management_id: current_management.id).count %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <% end %>
          <%= link_to managements_contacts_path do %>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-warning text-center">
                                  <i class="pe-7s-users"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Contacts</p>
                                  <%= Contact.count %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <% end %>
          <%= link_to managements_teams_path do %>
          <div class="col-lg-3 col-sm-6">
              <div class="card">
                  <div class="content">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="icon-big icon-warning text-center">
                                  <i class="pe-7s-users"></i>
                              </div>
                          </div>
                          <div class="col-xs-7">
                              <div class="numbers">
                                  <p>Team Member</p>
                                  <%= Team.count %>
                              </div>
                          </div>
                      </div>
                      <div class="footer">
                          <hr />
                          <div class="stats">
                              <i class="ti-reload"></i> Updated now
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <% end %>

        </div>
      </div>
    </div>

app/views/managements/show.html.erb
<h1>Management#show</h1>
<p>Find me in app/views/management/show.html.erb</p>